#!/bin/sh

set -e

echo ""
echo "  Emerson's Game"
echo ""

if test ! $(which bundler); then
  echo "  x You need to install Bundler:"
  echo "    gem install bundler"
  exit
else
  echo "  + Bundler found."
fi

if test ! $(which yarn); then
  echo "  x You need to install Yarn:"
  echo "    npm install -g yarn"
  exit
else
  echo "  + Yarn found."
fi

echo "  + Installing dependencies..."
bundle install --quiet
yarn install --silent --no-progress

echo "  + Running migrations..."
rails db:drop
rails db:create
rails db:migrate

echo "  + Seeding data..."
rails db:seed

echo ""
echo "  We're ready to rock!"
